### ISSUE TITLE
Problems importing the module

### ISSUE THREAD

**Issue by Alssdev** [theogravity/express-session-sqlite#2]
Hello, I have a problem when importing the module in my application since, I work working with **NodeJs**, I am using *'require'* not *'import'*. The problem is that Node doesn't recognize the module as the function it is.

In the documentation the **module** is used as a **function]**, to create another object, but this is the error:
![image](https://user-images.githubusercontent.com/49174467/94345514-a474d280-ffe3-11ea-91f1-028cf29f51af.png)

that's how I'm importing it:
![image](https://user-images.githubusercontent.com/49174467/94345554-f4539980-ffe3-11ea-9a77-d5fba0c30b36.png)

It would help me a lot to know how I can import it using 'require'

**Comment by theogravity** [comment]
require().default

**Comment by Alssdev** [comment]
thank you very much, it worked for me
