### ISSUE TITLE
How to use with JS?

### ISSUE THREAD

**Issue by kilasuelika** [theogravity/express-session-sqlite#5]
I dont't know how to use it in JS.

Direct using `import sqliteStoreFactory from 'express-session-sqlite'`  in main.js result in error. I tried 
```
const { sqliteStoreFactory } = require("express-session-sqlite");

const SqliteStore = sqliteStoreFactory(session);
```
It says `sqliteStoreFactory` is not a function.

I also tried `sqliteStoreFactory.sqliteStoreFactory(session)`, no luck.

**Comment by theogravity** [comment]
Try

`require("express-session-sqlite").default`

**Comment by oliverpechey** [comment]
Thanks @theogravity, that works for me

**Comment by dudeboy96** [comment]
Big help @theogravity  thanks a lot my dude!

**Comment by natsu90** [comment]
> Try
> 
> `require("express-session-sqlite").default`

for those doing in Typescript; `const SqliteStore = sqliteStoreFactory.default(sessions)`
